\documentclass{article}
\usepackage[portrait, headheight = 0cm, margin=0.25cm, top = 0.25cm]{geometry} 
\usepackage{graphicx}
\usepackage[dvipsnames,table]{xcolor}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{pdfpages}
\usepackage[export]{adjustbox} 
\usepackage{booktabs}
\usepackage{tikz}
\usetikzlibrary{shadings,arrows.meta,positioning,calc,intersections}
\usepackage{hyperref}
\usepackage[most]{tcolorbox}
\usepackage{array} % ensure m{} columns work
\usepackage{enumitem}  % to control list spacing
<<setup, include=FALSE>>=
run_code <- FALSE   # or FALSE to disable execution
@

<<, engine='bash', eval=run_code, include=FALSE>>=
python lyapunov1.py --spec \
'rgb:mh_eq:1:warmwhite:sand:maroon,[logistic:B6A6:2.52:3.46:3.65:4,eq933:A5B5:-.25:-.25:1.25:1.25,parasite:-.1:0:4:7,heart:0:0:5:5],a:2.5' \
--pix 2500 --out lyap1.png --thumb 5000
@



\title{
\vskip 1cm
{\bf\huge Lyapunov Exponent Fields}
\vskip 3cm
\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=15cm, height=15cm]{lyap1.png}}
\end{center}
\vskip 1cm
}
\author{Wigerich}

\begin{document}
\setlength{\fboxsep}{0pt} % no padding
\maketitle

\newpage
\tableofcontents

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap2.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:logistic:B6A6:2.52:3.46:3.65:4,rgb:mh_eq:1:deepskyblue:sand:ecarlate:2048' \
--pix 5000 --out lyap2.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} hist 3,3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap2_hist_3_3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:logistic:B6A6:2.52:3.46:3.65:4,rgb:mh_eq:1:black:black:white,hist:3:3' \
--pix 5000 --out lyap2_hist_3_3.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap2_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:logistic:B6A6:2.52:3.46:3.65:4,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap2_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} marvel comics palette mosaic }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap2m4.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'logistic:B6A6:2.52:3.46:3.65:4,rgb:multi:${glp("^marvel",9)}' \
--pix 2000 --out lyap2m4.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\newpage
\section{{\tt kicked}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:kicked:BA,ll:-3.215:-2.45,ul:-6.35:0.9325,lr:1.4325:1.85744,a:0.3,b:3,rgb:mh_eq:1:sienna:sand:seagreen' \
--pix 5000 --out lyap3.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\newpage
\section{{\tt kicked} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap3_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:kicked:BA,ll:-3.215:-2.45,ul:-6.35:0.9325,lr:1.4325:1.85744,a:0.3,b:3,rgb:mh_eq:1:sienna:sand:seagreen,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap3_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt kicked} winter painting palette mosaic }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap3m2.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'kicked:BA,ll:-3.215:-2.45,ul:-6.35:0.9325,lr:1.4325:1.85744,a:0.3,b:3,rgb:multi:${glp("^winter",9)}' \
--pix 2000 --out lyap3m2.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt econ}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap_fig810.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'econ882:BA:-3:1.65:-1:2.5,gamma:1,ll:-1:1.65,ul:-3:1.65,lr:-1:2.5,rgb:mh_eq:1:white:black:black' \
--pix 5000 --out lyap_fig810.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt fishery} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap_fishery_fig813.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'fishery,ll:-0.033:0,ul:-0.033:0.105,lr:0:0,x0:0.5,y0:0.5,trans:5,iter:20,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap_fishery_fig813.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt fishery} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap_fishery_fig813_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:fishery,ll:-0.033:0,ul:-0.033:0.105,lr:0:0,x0:0.5,y0:0.5,trans:5,iter:20,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap_fishery_fig813_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt fishery}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap_fishery_fig812.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'fishery:0:-20:10:10,ad:first,ap:second,bd:-0.005,cd:-0.05,bp:-0.04,cp:0.007,x0:0.5,y0:0.5,trans:100,iter:200,rgb:multi:bauhaus_primary_13' \
--pix 5000 --out lyap_fishery_fig812.png
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq827}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap_817_eq827.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq827:B5AA,ll:-15:-4.3,ul:-15:11,lr:35:-4.3,rgb:mh_eq:0.5:black:black:white' \
--pix 5000 --out lyap_817_eq827.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt cardiac} lyapunov }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap4.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:cardiac,ll:0:20,ul:0:140,lr:150:20,rgb:mh_eq:1:firebrick:silver:avocado' \
--pix 5000 --out lyap4.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt cardiac} histogram }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap4_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:cardiac,ll:0:20,ul:0:100,lr:100:20,rgb:mh_eq:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap4_hist.png --thumb 5000
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt predprey}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap5.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'predprey:BA,ll:-.6:.75,ul:-.6:5,lr:5.5:.75,b:3.569985,rgb:mh:0.25:red:black:yellow' \
--pix 5000 --out lyap5.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt predprey} winter palette mosaic }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap5m1.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'predprey:BA,ll:-.6:.75,ul:-.6:5,lr:5.5:.75,b:3.569985,rgb:multi:${glp("^winter",9)}' \
--pix 2000 --out lyap5m1.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt parasite}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap6.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'parasite,a:3.1,rgb:mh:0.25:red:black:yellow' \
--pix 5000 --out lyap6.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt parasite} winter palette mosaic }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap6m1.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'parasite,a:3.1,rgb:multi:${glp("^winter",9)}' \
--pix 2000 --out lyap6m1.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt henzi} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap7.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'henzi:BA,ll:1.483:2.35,ul:2.15:1.794,lr:-.35:.15,b:0.994,rgb:mh_eq:1:warmwhite:khaki:teal:2048' \
--pix 5000 --out lyap7.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt henzi} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap7_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:henzi:BA,ll:1.483:2.35,ul:2.15:1.794,lr:-.35:.15,b:0.994,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap7_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt henzi} winter painting palette mosaic }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap7m1.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'henzi:BA,ll:1.483:2.35,ul:2.15:1.794,lr:-.35:.15,b:0.994,rgb:multi:${glp("^winter",9)}'\
--pix 2000 --out lyap7m1.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt adbash} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap8.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'adbash:AB,ll:-4.7:0,ul:0:4.7,lr:0:-4.7,a:1,rgb:mh_eq:1:firebrick:olive:tan' \
--pix 5000 --out lyap8.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt adbash} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap8_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:adbash:AB,ll:-4.7:0,ul:0:4.7,lr:0:-4.7,a:1,rgb:mh_eq:1:firebrick:olive:tan,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap8_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt degn} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap9_1.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'degn,k:1,ll:0.2:-1.15,ul:0.2:1.15,lr:2.9:-1.15,rgb:mh_eq:1:firebrick:darkgrey:sunset' \
--pix 5000 --out lyap9_1.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt degn} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap9_1_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:degn,k:1,ll:0.2:-1.15,ul:0.2:1.15,lr:2.9:-1.15,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap9_1_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt degn nn} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap9.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:degn_nn:-7.5:-2:7.5:2,a:0.1,b:1e8,rgb:mh:0.25:firebrick:darkgrey:sunset' \
--pix 10000 --out lyap9.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt degn nn} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap9_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:degn_nn:-7.5:-2:7.5:2,a:0.1,b:1e8,rgb:mh:0.25:firebrick:darkgrey:sunset,hist:{0:3}:{0:3}' \
--pix 5000 --out lyap9_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn941} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap941.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eqn941,ll:-10:-2.9,ul:-10:2.9,lr:10:-2.9,rgb:mh_eq:1:firebrick:darkgrey:sunset' \
--pix 5000 --out lyap941.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn941} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap941_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eqn941,ll:-10:-2.9,ul:-10:2.9,lr:10:-2.9,rgb:mh_eq:1:firebrick:darkgrey:sunset,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap941_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn941} r vs K, lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap941_a.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eqn941,b:1.075,k:first,r:second,ll:-0.7:-3.9,ul:-0.7:3.9,lr:0.7:-3.9,rgb:mh_eq:1:firebrick:darkgrey:sunset' \
--pix 5000 --out lyap941_a.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn941} r vs K, hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap941_a_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eqn941,b:1.075,k:first,r:second,ll:-0.7:-3.9,ul:-0.7:3.9,lr:0.7:-3.9,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap941_a_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn950} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap950.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq950:BA,b:1.9,x0:1.5,ll:-3.8:0,ul:-3.8:6,lr:3.8:0,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap950.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn950} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap950_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq950:BA,b:1.9,x0:1.5,ll:-3.8:0,ul:-3.8:6,lr:3.8:0,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap950_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn951} lyapunov }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{eq951.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq951:B8A8:-3:-0.75:-1:0,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out eq951.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn951} hist }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{eq951_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq951:B8A8:-3:-0.75:-1:0,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out eq951_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn952} lyapunov }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap952.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq952:AB,b:3.2,x0:0.5,ll:-1.52:1.33,ul:1.33:4.18,lr:1.33:-1.52,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap952.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn952} hist }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap952_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq952:AB,b:3.2,x0:0.5,ll:-1.52:1.33,ul:1.33:4.18,lr:1.33:-1.52,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap952_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn959} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap959.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq959:AB,b:1.16,x0:0.5,ll:-0.025:-2.3,ul:-2.3:-0.025,lr:4.2:1.925,trans:100,iter:200,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap959.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn959} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap959_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq959:AB,b:1.16,x0:0.5,ll:-0.025:-2.3,ul:-2.3:-0.025,lr:4.2:1.925,trans:100,iter:200,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap959_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn965} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap965.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq965:A4B4,b:1,x0:0.5,ll:-15.555:3.8982,ul:-3.1422:16.126,lr:3.7129:-15.6612,trans:500,iter:500,rgb:multi:debug_saw_luma_13' \
--pix 5000 --out lyap965.png  
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn965} entropy}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap965_entropy.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq965:A4B4,b:1,x0:0.5,ll:-15.555:3.8982,ul:-3.1422:16.126,lr:3.7129:-15.6612,trans:500,iter:500,rgb:multi:debug_saw_luma_13,entropy' \
--pix 5000 --out lyap965_entropy.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn965} hist:3:1}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap965_hist_3_1.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq965:A4B4,b:1,x0:0.5,ll:-15.555:3.8982,ul:-3.1422:16.126,lr:3.7129:-15.6612,trans:500,iter:500,rgb:multi:debug_saw_luma_13,hist:3:1' \
--pix 5000 --out lyap965_hist_3_1.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn965} hist mosaic}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap965_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq965:A4B4,b:1,x0:0.5,ll:-15.555:3.8982,ul:-3.1422:16.126,lr:3.7129:-15.6612,trans:500,iter:500,rgb:multi:debug_saw_luma_13,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap965_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn970} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap970_fig9138.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq970:AB,ll:6.2879:-4.697,ul:6.2879:3.447,lr:9.4334:-4.697,b:1.5,x0:0.5,trans:50,iter:100,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap970_fig9138.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn970} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap970_fig9138_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq970:AB,ll:6.2879:-4.697,ul:6.2879:3.447,lr:9.4334:-4.697,b:1.5,x0:0.5,trans:50,iter:100,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 5000 --out lyap970_fig9138_hist.png --thumb 5000
@



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn971} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap971_fig9139.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq971:AAABBB,ll:-2.7:-1.08,ul:1.08:2.7,lr:-1.08:-2.7,b:1.5,x0:0.5,trans:25,iter:50,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap971_fig9139.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn971} entropy}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap971_fig9139_entropy.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq971:AAABBB,ll:-2.7:-1.08,ul:1.08:2.7,lr:-1.08:-2.7,b:1.5,x0:0.5,trans:25,iter:50,rgb:mh_eq:1:black:black:white,entropy' \
--pix 5000 --out lyap971_fig9139_entropy.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn971} histogram}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap971_fig9139_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq971:AAABBB,ll:-2.7:-1.08,ul:1.08:2.7,lr:-1.08:-2.7,b:1.5,x0:0.5,trans:25,iter:50,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 5000 --out lyap971_fig9139_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn974} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap974_fig9142.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq974:A6BB,ll:-2.62:0.36,ul:-2.62:26.04,lr:2.6:0.36,b:1.8,x0:0.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white,entropy' \
--pix 5000 --out lyap974_fig9142.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn974} hist:0:3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap974_fig9142_hist_0_3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:eq974:A6BB,ll:-2.62:0.36,ul:-2.62:26.04,lr:2.6:0.36,b:1.8,x0:0.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white,hist:0:3' \
--pix 5000 --out lyap974_fig9142_hist_0_3.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn974} hist 0..3,0..3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap974_fig9142_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq974:A6BB,ll:-2.62:0.36,ul:-2.62:26.04,lr:2.6:0.36,b:1.8,x0:0.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap974_fig9142_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn978} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap978_fig9147.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq978:AB,ll:0:0,ul:0:2,lr:2:0,b:0.5,x0:0.5,trans:500,iter:1000,rgb:mh_eq:1:black:black:white' \ 
--pix 5000 --out lyap978_fig9147.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn978} entropy}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap978_fig9147_entropy.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq978:AB,ll:0:0,ul:0:2,lr:2:0,b:0.5,x0:0.5,trans:500,iter:1000,rgb:mh_eq:1:black:black:white,entropy' \
--pix 5000 --out lyap978_fig9147_entropy.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn978} hist 3,3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap978_fig9147_hist_3_3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq978:AB,ll:0:0,ul:0:2,lr:2:0,b:0.5,x0:0.5,trans:500,iter:1000,rgb:mh_eq:1:black:black:white,hist:3:3' \
--pix 5000 --out lyap978_fig9147_hist_3_3.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn978} histogram}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap978_fig9147_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq978:AB,ll:0:0,ul:0:2,lr:2:0,b:0.5,x0:0.5,trans:500,iter:1000,rgb:mh_eq:1:black:black:white,hist' \
--pix 5000 --out lyap978_fig9147_hist.png
@
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn979} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap979_fig9149.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq979:0:0:4:4,x0:0.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap979_fig9149.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn979} entropy}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap979_fig9149_entropy.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq979:0:0:4:4,x0:0.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white,entropy' \
--pix 5000 --out lyap979_fig9149_entropy.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn979} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap979_fig9149_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq979:0:0:4:4,x0:0.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap979_fig9149_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn979} lyapunov 9.148}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap979_fig9148.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:eq979_ab:AB,ll:2.7741:3.1152,ul:2.7785:2.6996,lr:2.5144:3.1125,b:1,x0:1.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap979_fig9148.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn979} hist 0,3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap979_fig9148_hist_0_3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq979_ab:AB,ll:2.7741:3.1152,ul:2.7785:2.6996,lr:2.5144:3.1125,b:1,x0:1.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white,hist:0:3' \
--pix 5000 --out lyap979_fig9148_hist_0_3.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn979} hist 9.148}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap979_fig9148_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:eq979_ab:AB,ll:2.7741:3.1152,ul:2.7785:2.6996,lr:2.5144:3.1125,b:1,x0:1.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap979_fig9148_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn980} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap980_fig9150.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
 'map:eq980_ab:AB,b:0.9,x0:1.4,trans:100,iter:200,ll:-5.5388:2.20,ul:-5.5388:3.6217,lr:-4.94297:2.20,rgb:mh_eq:1:black:black:white' \
 --pix 5000 --out lyap980_fig9150.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn980} histogram}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap980_fig9150_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
 'map:eq980_ab:AB,b:0.9,x0:1.4,trans:100,iter:200,ll:-5.5388:2.20,ul:-5.5388:3.6217,lr:-4.94297:2.20,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
 --pix 2000 --out lyap980_fig9150_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn980} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap980_fig9151.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq980,ll:0.26:1.36,ul:0.26:3.85,lr:1.44:1.36,x0:0.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap980_fig9151.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn980} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap980_fig9151_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq980,ll:0.26:1.36,ul:0.26:3.85,lr:1.44:1.36,x0:0.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap980_fig9151_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn981} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap981_fig9153.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq981:AB,ll:-4:-12,ul:-12:4,lr:12:-4,b:2,x0:0.5,trans:200,iter:200,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap981_fig9153.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn981} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap981_fig9153_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq981:AB,ll:-4:-12,ul:-12:4,lr:12:-4,b:2,x0:0.5,trans:200,iter:200,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap981_fig9153_hist.png --thumb 5000
@




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn985} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap985_fig9160.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq985:AB,ll:2.0292:2.3214,ul:2.5354:2.832,lr:2.3177:2.0354,b:0.5,x0:0.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap985_fig9160.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn985} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap985_fig9160_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq985:AB,ll:2.0292:2.3214,ul:2.5354:2.832,lr:2.3177:2.0354,b:0.5,x0:0.5,trans:100,iter:200,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap985_fig9160_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn968} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap968.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq968:A3B3,b:1,x0:0.9,ll:2.21248:1.53388,ul:2.21248:1.61899,lr:2.33097:1.53388,trans:100,iter:100,rgb:multi:debug_saw_luma_13' \
--pix 5000 --out lyap968.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn968} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap968_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq968:A3B3,b:1,x0:0.9,ll:2.21248:1.53388,ul:2.21248:1.61899,lr:2.33097:1.53388,trans:100,iter:100,rgb:multi:debug_saw_luma_13,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap968_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn953} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap953.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq953:A3B3,b:4,x0:0.5,ll:1.0913:1.2253,ul:1.2444:1.3784,lr:1.2253:1.0913,trans:400,iter:400,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap953.png  
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn953} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap953_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq953:A3B3,b:4,x0:0.5,ll:1.0913:1.2253,ul:1.2444:1.3784,lr:1.2253:1.0913,trans:400,iter:400,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap953_hist.png  --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn961} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap961.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq961:A5B5,b:5,x0:0.5,ll:1.3341:4.7792,ul:3.2843:6.7294,lr:4.7795:1.3338,trans:25,iter:50,rgb:mh_eq:0.33:black:black:white' \
--pix 5000 --out lyap961.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn961} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap961_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq961:A5B5,b:5,x0:0.5,ll:1.3341:4.7792,ul:3.2843:6.7294,lr:4.7795:1.3338,trans:25,iter:50,rgb:mh_eq:0.33:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap961_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt henon}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap10.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'henon,ll:1.1:0.1,ul:1.1:.4,lr:1.65:0,rgb:mh:0.25:firebrick:darkgrey:sunset' \
--pix 5000 --out lyap10.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt henon} winter palette mosaic }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap10m1.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'henon,ll:1.1:0.1,ul:1.1:.4,lr:1.65:0,rgb:multi:${glp("^winter",9)}' \
--pix 2000 --out lyap10m1.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt henon} beach palette mosaic }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap10m2.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'henon,ll:1.1:0.1,ul:1.1:.4,lr:1.65:0,rgb:multi:${glp("^beach",9)}' \
--pix 2000 --out lyap10m2.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt kst2d}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap11.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'kst2d,rgb:mh:0.25:firebrick:darkgrey:sunset' \
--pix 5000 --out lyap11.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic2d}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap12.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'logistic2d,ll:0:0.65,ul:0:2.95,lr:1:.65,a:0.4,rgb:mh_eq:1:firebrick:black:sunset:2048' \
--pix 5000 --out lyap12.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt heart}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap13.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'heart:-2:-2:2:2,a:2.25,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap13.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn3} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap14.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:nn3,rgb:mh_eq:1:black:black:white' \
--pix 5000 --out lyap14.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn3} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap14_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:nn3,rgb:mh_eq:1:black:black:white,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap14_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn4}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap15.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'nn4,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap15.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn5}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap16.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'nn5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap16.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn8}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap17.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'nn8,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap17.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn8} zoom}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap17zoom1.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'nn8:2:2:11:11,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap17zoom1.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn8} take 2 }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap17t2.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'nn8,rgb:mh_eq:1:royalblue:black:platinum' \
--pix 5000 --out lyap17t2.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn8} metal palette mosaic }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap17t3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'nn8,rgb:multi:${glp("^metal",9)}' \
--pix 2000 --out lyap17t3.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn8} marvel comics palette mosaic }

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap17t4.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'nn8,rgb:multi:${glp("^marvel",9)}' \
--pix 2000 --out lyap17t4.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn9}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap18.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:nn9,ll:0:-15,ul:15:0,lr:-15:0,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap18.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt nn9} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap18_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:nn9,ll:0:-15,ul:15:0,lr:-15:0,rgb:mh_eq:1:firebrick:black:sunset,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap18_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq826} lyapunov, take 1}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap19.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'eq826:AABB,b:11,ll:23.5:32.7,ul:33.2:42.5,lr:32.8:23.5898,rgb:mh_eq:1:royalblue:black:platinum' \
--pix 5000 --out lyap19.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq826} hist, take 1}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap19_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq826:AABB,b:11,ll:23.5:32.7,ul:33.2:42.5,lr:32.8:23.5898,rgb:mh_eq:1:royalblue:black:platinum,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap19_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq826} bugliaca mosaic}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap19t2.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq826:AABB,b:11,ll:23.5:32.7,ul:33.2:42.5,lr:32.8:23.5898,rgb:multi:${glp("^bugliaca",9)}' \
--pix 5000 --out lyap19t2.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq97} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap20.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'map:eq97,ll:2:.5,ul:2:1.4,lr:10.2,.5,rgb:mh_eq:1:seagreen:black:copper:2048' \
--pix 5000 --out lyap20.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq97} hist 1}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap20_hist_1.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq97,ll:2:.5,ul:2:1.4,lr:10.2,.5,rgb:mh_eq:1:seagreen:black:copper,hist:0:6' \
--pix 5000 --out lyap20_hist_1.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq97} hist 2}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap20_hist_2.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq97,ll:2:.5,ul:2:1.4,lr:10.2,.5,rgb:mh_eq:1:seagreen:black:copper,trans:200,hist:200,hist:3:6' \
--pix 5000 --out lyap20_hist_2.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq97} hist 3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap20_hist_3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq97,ll:2:.5,ul:2:1.4,lr:10.2,.5,rgb:mh_eq:1:seagreen:black:copper,trans:200,hist:200,hist:4:2' \
--pix 5000 --out lyap20_hist_3.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq95}}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap21.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
 python lyapunov1.py --spec \
'eq95,a:0.25,ll:0.912:0,ul:0.912:1.1735,lr:2.496:0,rgb:mh_eq:1:seagreen:black:copper:2048' \
--pix 5000 --out lyap21.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq95} hist 6,6}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap21_hist_6_6.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq95,a:0.25,ll:0.912:0,ul:0.912:1.1735,lr:2.496:0,rgb:mh_eq:1:seagreen:black:copper:2048,hist:6:6' \
--pix 5000 --out lyap21_hist_6_6.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq95} hist 5,2}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap21_hist_5_2.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq95,a:0.25,ll:0.912:0,ul:0.912:1.1735,lr:2.496:0,rgb:mh_eq:1:seagreen:black:copper:2048,hist:5:2' \
--pix 5000 --out lyap21_hist_5_2.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq933} lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap22.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq933:B8A8,rgb:palette:bauhaus_primaries:0.5:2048' \
--pix 5000 --out lyap22.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq933} hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap22_hist_3_3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq933:B8A8,rgb:palette:bauhaus_primaries:0.5:2048,hist:3:3' \
--pix 5000 --out lyap22_hist_3_3.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 1}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap23.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:A6B6,b:1.95,ll:3.11:2.02,ul:2.21:1.13,lr:2.033:3.109,rgb:palette:itten_blue_orange' \
--pix 5000 --out lyap23.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 1, hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap23_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:A6B6,b:1.95,ll:3.11:2.02,ul:2.21:1.13,lr:2.033:3.109,rgb:palette:itten_blue_orange,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap23_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 1, beach mosaic}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap23t3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A6B6,b:1.95,ll:3.11:2.02,ul:2.21:1.13,lr:2.033:3.109,rgb:multi:${glp("^beach",9)}' \
--pix 2000 --out lyap23t3.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 2, lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap24.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A10B10,b:1.7,ll:0.203:2.748,ul:0.167:2.784,lr:0.264:2.809,rgb:palette:swiss_modern' \
--pix 5000 --out lyap24.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 2, hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap24_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:A10B10,b:1.7,ll:0.203:2.748,ul:0.167:2.784,lr:0.264:2.809,rgb:palette:swiss_modern,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap24_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap25.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:AB,b:2.5,ll:-2:-2,ul:-2:2,lr:2:-2,rgb:palette:cyberpunk_neon' \
--pix 5000 --out lyap25.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 3, hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap25_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:AB,b:2.5,ll:-2:-2,ul:-2:2,lr:2:-2,rgb:palette:cyberpunk_neon,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap25_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 3, hist 3,3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap25_hist_3_3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:AB,b:2.5,ll:-2:-2,ul:-2:2,lr:2:-2,rgb:palette:cyberpunk_neon,hist:3:3' \
--pix 5000 --out lyap25_hist_3_3.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 3, hist 0,0}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap25_hist_0_0.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:AB,b:2.5,ll:-2:-2,ul:-2:2,lr:2:-2,rgb:palette:cyberpunk_neon,hist:0:0' \
--pix 5000 --out lyap25_hist_0_0.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 3, take 2}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap25t2.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:AB,b:2.5,ll:-2:-2,ul:-2:2,lr:2:-2,rgb:multi:${glp("^blaue_reiter",9)}' \
--pix 2000 --out lyap25t2.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 3, take 3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap25t3.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:AB,b:2.5,ll:-2:-2,ul:-2:2,lr:2:-2,rgb:multi:${glp("^washington",9)}' \
--pix 2000 --out lyap25t3.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 3, beach mosaic}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap25t4.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:AB,b:2.5,ll:-2:-2,ul:-2:2,lr:2:-2,rgb:multi:${glp("^beach",9)}' \
--pix 2000 --out lyap25t4.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 3, take 5}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap25t5.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:AB,b:2.5,ll:-2:-2,ul:-2:2,lr:2:-2,rgb:multi:${glp("^winter",9)}' \
--pix 2000 --out lyap25t5.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 4}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap26.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A6B6,b:1.95,ll:0.705:-.453,ul:1.15:-.847,lr:0.075:-1.165,rgb:palette:midcentury_earth' \
--pix 5000 --out lyap26.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 5}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap27.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A10B10,b:2,ll:0.634:.127,ul:1.06:.361,lr:0.408:.538,rgb:palette:thermal_blackbody' \
--pix 5000 --out lyap27.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 6, lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap28.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A6B6,b:2.6,ll:3.145:1.715,ul:2.966:1.843,lr:3.283:1.909,rgb:palette:scientific_blue' \
--pix 5000 --out lyap28.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 6, hist 0,0}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap28_hist_0_0.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:A6B6,b:2.6,ll:3.145:1.715,ul:2.966:1.843,lr:3.283:1.909,rgb:palette:scientific_red_blue,hist:0:0' \
--pix 5000 --out lyap28_hist_0_0.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 6, hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap28_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:A6B6,b:2.6,ll:3.145:1.715,ul:2.966:1.843,lr:3.283:1.909,rgb:palette:scientific_red_blue,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap28_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 7, lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap29.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A6B6,b:2.7,ll:1.225:1.015,ul:0.985:0.775,lr:1.015:1.225,rgb:palette:vintage_print' \
--pix 5000 --out lyap29.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 7, hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap29_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:A6B6,b:2.7,ll:1.225:1.015,ul:0.985:0.775,lr:1.015:1.225,rgb:palette:vintage_print,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap29_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 8, lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap30.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:AB,b:2.8,ll:0:0,ul:0:10,lr:8.8:0,rgb:palette:fauvism_wild' \
--pix 5000 --out lyap30.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 8, hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap30_hist.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq947:AB,b:2.8,ll:0:0,ul:0:10,lr:8.8:0,rgb:palette:fauvism_wild,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap30_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eq947} location 9}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap31.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A3B3,b:2.05,ll:2.157:3.11,ul:1.282:2.235,lr:3.11:2.158,rgb:palette:bauhaus_blue_yellow' \
--pix 5000 --out lyap31.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} location 1}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap32.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'logistic:AB,ll:2:2,ul:2:4,lr:4:2,rgb:palette:impressionist_pastel' \
--pix 5000 --out lyap32.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} location 2}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap33.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'logistic:AB,x0:0.5,ll:3.817:3.817,ul:3.817:3.868,lr:3.868:3.817,rgb:palette:expressionist_moody' \
--pix 5000 --out lyap33.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} location 3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap34.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'logistic:A3B2,x0:0.5,ll:3.8358:3.59,ul:3.8358:3.6,lr:3.8405:3.59,rgb:palette:brutalist_concrete' \
--pix 5000 --out lyap34.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} location 4}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap35.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'logistic:ABAABBAAABBB,x0:0.5,ll:3.18:3.73,ul:3.18:3.96,lr:3.52:3.73,rgb:palette:minimal_blue' \
--pix 5000 --out lyap35.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} location 5}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap36.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'logistic:A5B5,x0:0.5,ll:3.44:3.141,ul:3.6435:3.27,lr:3.625:3.849,rgb:palette:material_teal_orange' \
--pix 5000 --out lyap36.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} location 6}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap37.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'logistic:ABAABBA3B3AABBAB,x0:0.8315,ll:1.569:3.793,ul:1.569:3.9385,lr:1.602:3.793,rgb:palette:terrain_elevation' \
--pix 5000 --out lyap37.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} location 7}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap38.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'logistic:AABABAB,x0:.5,ll:2.759:3.21,ul:2.759:4,lr:3.744:3.21,rgb:palette:oceanographic_deep' \
--pix 5000 --out lyap38.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt logistic} location 8}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap39.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'logistic:AABAB,x0:.5,ll:3.45:3.54,ul:3.45:3.67,lr:3.61:3.54,rgb:palette:psychedelic_70s' \
--pix 5000 --out lyap39.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 96} location 1}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap40.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq96:AB,x0:.7,a:0.9935,ll:3.815:3.838,ul:3.848:3.871,lr:3.839:3.814,rgb:palette:artdeco_jewel' \
--pix 5000 --out lyap40.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 96} location 2}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap41.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq96:BBABABA,x0:.499,a:0.907,ll:3.8175:3.8138,ul:3.8175:3.8181,lr:3.8097:3.8138,rgb:palette:stone_bronze' \
--pix 5000 --out lyap41.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 96} location 3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap42.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq96:AB,x0:.499,a:0.908,ll:3.799:3.8143,ul:3.8115:3.828,lr:3.8169:3.7980,rgb:palette:wood_copper:0.33' \
--pix 5000 --out lyap42.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 96} location 4}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap43.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq96:AB,x0:.499,a:0.907,ll:3.8109:3.8109,ul:3.8109:3.8207,lr:3.8207:3.8109,rgb:multi:marvel_spiderman_long' \
--pix 5000 --out lyap43.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 947} location 1}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap44.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A10B10,x0:.0,b:1.7,ll:0.203:2.748,ul:0.167:2.784,lr:0.264:2.809,rgb:multi:marvel_ironman_long' \
--pix 5000 --out lyap44.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 947} location 2}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap45.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:AB,x0:.0,b:2.5,ll:0:0,ul:0:10,lr:8.8:0,rgb:multi:marvel_captain' \
--pix 5000 --out lyap45.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 947} location 3}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap46.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A6B6,x0:.0,b:1.95,ll:0.705:−0.453,ul:1.15:−0.847,lr:0.075:−1.165,rgb:multi:marvel_hulk_long' \
--pix 5000 --out lyap46.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 947} location 4}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap47.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A10B10,x0:1,b:2,ll:0.634:0.127,ul:1.06:0.361,lr:0.408:0.538,rgb:multi:marvel_cosmic_long' \
--pix 5000 --out lyap47.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 947} location 4, mosaic 1}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap48.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A10B10,x0:1,b:2,ll:0.634:0.127,ul:1.06:0.361,lr:0.408:0.538,rgb:multi:${glp("^metal",9)}' \
--pix 2000 --out lyap48.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 947} location 4, mosaic 2}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap49.png}}
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq947:A10B10,x0:1,b:2,ll:0.634:0.127,ul:1.06:0.361,lr:0.408:0.538,rgb:multi:${glp("^bauhaus",9)}' \
--pix 2000 --out lyap49.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} location fig 9.32}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_1.png}}
fig 9.32
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:-1,b:2.25,c:0,d:2,ll:4.4348:4.5432,ul:4.5546:4.663,lr:4.5522:4.4258,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_1.png 
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\section{{\tt eqn 948} location fig 9.33}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_2.png}}
fig 9.33
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0.6,b:1.5,c:0,d:2,ll:5.13:5.375,ul:5.433:5.678,lr:5.375:5.13,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_2.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\section{{\tt eqn 948} location fig 9.34}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_3.png}}
fig 9.34
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:2.4,b:2,c:0,d:2,ll:0.796:0.966,ul:0.918:1.088,lr:0.966:0.796,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_3.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\section{{\tt eqn 948} location fig 9.35}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_4.png}}
fig 9.35
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:-0.4,b:2,c:0,d:2,ll:5.5113:5.5933,ul:5.615:5.697,lr:5.5933:5.5113,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_4.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} location fig 9.36}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_5.png}}
fig 9.36
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:-1.25,b:1.5,c:0,d:2,ll:4.382:4.733,ul:4.771:5.122,lr:4.732:4.38,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_5.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} location fig 9.37}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_6.png}}
fig 9.37
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:-0.2,b:2,c:0,d:2,ll:4.569:4.67,ul:4.661:4.762,lr:4.67:4.569,trans:2000,iter:2000,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_6.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} location fig 9.38}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_7.png}}
fig 9.38 (fixme its A2B2)
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0.7,b:2,c:0,d:2,ll:2.33:1,ul:2.33:1.77,lr:3.61:1,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_7.png 
@



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.39
\newpage
\section{{\tt eqn 948} location fig 9.39}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_9.png}}
fig 9.39
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0.7,b:2,c:0,d:2,ll:5.009:5.123,ul:5.059:5.173,lr:5.123:5.009,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_9.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.40
\newpage
\section{{\tt eqn 948} location fig 9.40}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_10.png}}
fig 9.40
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0,b:1.6,c:1.5,d:2,ll:3.793:3.907,ul:3.941:4.055,lr:3.905:3.795,x0:0.3,iter:200,trans:100,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_10.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} location fig 9.41}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_11.png}}
fig 9.41
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0,b:1.8,c:1.5,d:2,ll:2.305:2.357,ul:2.305:2.415,lr:2.365:2.357,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_11.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} location 12, lyapunov}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_12.png}}
\end{center}
no fig
\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0.2,b:2.3,c:0,d:1,ll:0.13:−1.0137,ul:−0.3237:−1.4212,lr:−0.7637:-1.4212,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_12.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} location 12, hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_12_hist.png}}
\end{center}
no fig
\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A3B3,a:0.2,b:2.3,c:0,d:1,ll:0.13:−1.0137,ul:−0.3237:−1.4212,lr:−0.7637:-1.4212,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 2000 --out lyap948_12_hist.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.43
\newpage
\section{{\tt eqn 948} location fig 9.43}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_13.png}}
fig 9.43
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:1.8,c:1.5,d:2,ll:2.091:2.3,ul:2.349:2.558,lr:2.3:2.091,trans:1000,iter:1000,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_13.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.44
\newpage
\section{{\tt eqn 948} location fig 9.44}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_14.png}}
fig 9.44
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:2,c:1.25,d:2,ll:5.827:5.879,ul:5.864:5.916,lr:5.879:5.827,trans:200,iter:200,x0:1.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_14.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.45
\newpage
\section{{\tt eqn 948} location fig 9.45}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_15.png}}
fig 9.45
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:2,c:1.25,d:2,ll:3.002:3.27,ul:3.179:3.449,lr:3.272:3.003,trans:500,iter:500,x0:1.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_15.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.47
\newpage
\section{{\tt eqn 948} location fig 9.47}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_16.png}}
fig 9.47
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0,b:2,c:1.25,d:2,ll:3.203:3.257,ul:3.28:3.334,lr:3.257:3.203,trans:500,iter:500,x0:1.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_16.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.48
\newpage
\section{{\tt eqn 948} location fig 9.48}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_17.png}}
fig 9.48
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0,b:1.7,c:1.5,d:2,ll:5.6016:5.7464,ul:5.7962:5.941,lr:5.7464:5.6016,trans:200,iter:200,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_17.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.49
\newpage
\section{{\tt eqn 948} location fig 9.49}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_18.png}}
fig 9.49
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0,b:1.7,c:1.5,d:2,ll:3.394:3.278,ul:3.6105:3.4185,lr:3.4825:3.1416,trans:200,iter:200,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_18.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.50
\newpage
\section{{\tt eqn 948} location fig 9.50}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_19.png}}
fig 9.50
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:1,b:2.25,c:0,d:2,ll:2.446:1.074,ul:2.446:1.416,lr:3.18:1.074,trans:200,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_19.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.51
\newpage
\section{{\tt eqn 948} location fig 9.51}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_20.png}}
fig 9.51
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0.7,b:2,c:0,d:1,ll:0.95:1.1425,ul:1.0325:1.225,lr:1.1425:0.95,trans:200,iter:1000,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_20.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.52
\newpage
\section{{\tt eqn 948} location fig 9.52}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_21.png}}
fig 9.52
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:2.3,c:0,d:1,ll:−0.2:1.47325,ul:1.47325:−0.2,lr:0.93675:2.61,trans:300,iter:400,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_21.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.53
\newpage
\section{{\tt eqn 948} location fig 9.53}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_22.png}}
fig 9.53
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:-0.4,b:2,c:1.5,d:1,ll:5.15:5.405,ul:5.414:5.669,lr:5.405:5.15,trans:600,iter:600,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_22.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.54
\newpage
\section{{\tt eqn 948} location fig 9.54}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_23.png}}
fig 9.54
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0.7,b:2,c:1.25,d:1,ll:1.395:1.863,ul:1.771:2.24,lr:1.863:1.3962,trans:800,iter:800,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_23.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.55
\newpage
\section{{\tt eqn 948} location fig 9.55}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_24.png}}
fig 9.55
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:2.3,c:0.25,d:1,ll:-0.2:1.2,ul:0.8:2.2,lr:1.2:-0.2,trans:400,iter:1000,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_24.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.56
\newpage
\section{{\tt eqn 948} location fig 9.56}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_25.png}}
fig 9.56
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:2.3,c:0.15,d:1,ll:-1.52:-0.93,ul:-2.2:-0.93,lr:-1.52:-0.25,trans:300,iter:300,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_25.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.57
\newpage
\section{{\tt eqn 948} location fig 9.57}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_26.png}}
fig 9.57
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:2.3,c:0.25,d:1,ll:4.22:6.775,ul:5.285:6.4589,lr:3.802:5.3667,trans:200,iter:500,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_26.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.58
\newpage
\section{{\tt eqn 948} location fig 9.58}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_27.png}}
fig 9.58
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:1.25,b:2,c:0,d:1,ll:-1.26:-0.08,ul:-0.339:0.861,lr:-0.08:-1.2349,trans:100,iter:200,x0:1.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_27.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.59
\newpage
\section{{\tt eqn 948} location fig 9.59}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_28.png}}
fig 9.59
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0,b:1.8,c:1.5,d:1,ll:3.95:6.1,ul:3.95:7.8,lr:4.87:6.1,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_28.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.60
\newpage
\section{{\tt eqn 948} location fig 9.60}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_29.png}}
fig 9.60
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0,b:1.7,c:1.5,d:1,ll:-1.68:-0.64,ul:-0.64:0.4,lr:-0.64:-1.68,trans:100,iter:200,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_29.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.61
\newpage
\section{{\tt eqn 948} location fig 9.61}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_30.png}}
fig 9.61
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0,b:1.6,c:1.5,d:1,ll:1.885:2.55,ul:2.52:3.185,lr:2.55:1.885,trans:100,iter:200,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_30.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.62
\newpage
\section{{\tt eqn 948} location fig 9.62}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_31.png}}
fig 9.62
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:1.8,c:1.5,d:1,ll:0.16:1.41,ul:1.26:2.51,lr:1.41:0.16,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_31.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.63
\newpage
\section{{\tt eqn 948} location fig 9.63}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_32.png}}
fig 9.63
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:2.4,b:2,c:0,d:1,ll:0.37:1.67,ul:0.97:2.27,lr:1.67:0.37,trans:200,iter:400,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_32.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.64
\newpage
\section{{\tt eqn 948} location fig 9.64}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_33.png}}
fig 9.64
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0,b:2,c:1.25,d:1,ll:2.29:3.19,ul:2.887:3.787,lr:3.19:2.29,trans:100,iter:200,x0:1.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_33.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.66
\newpage
\section{{\tt eqn 948} location fig 9.66}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_34.png}}
fig 9.66
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0,b:2.25,c:-1,d:1,ll:4.06:4.151,ul:4.143:4.234,lr:4.151:4.06,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_34.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.67
\newpage
\section{{\tt eqn 948} location fig 9.67}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_35.png}}
fig 9.67
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:2,c:1.25,d:1,ll:1.6:2.76,ul:2.83:3.99,lr:2.76:1.6,trans:1000,iter:1000,x0:1.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_35.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.68
\newpage
\section{{\tt eqn 948} fig 9.68}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_fig968.png}}
fig 9.68
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0.1,b:2.3,c:0,d:1,ll:1.63:2.655,ul:2.655:3.68,lr:2.705:1.58,trans:100,iter:200,x0:0.7,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_fig968.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} fig 9.69}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_8.png}}
fig 9.69
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:-0.4,b:1.5,c:0,d:1,ll:1.19:1.87,ul:2.19:2.96,lr:1.95:1.1728,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_8.png 
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} fig 9.69, hist}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_8_hist.png}}
fig 9.69
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2,a:-0.4,b:1.5,c:0,d:1,ll:1.19:1.87,ul:2.19:2.96,lr:1.95:1.1728,rgb:mh_eq:1:firebrick:black:sunset,hist:{0:3}:{0:3}' \
--pix 2000 --out lyap948_8_hist.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} fig 9.69, hist,3,0}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_8_hist_3_0.png}}
fig 9.69
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2:-4:-4:4:4,a:-0.4,b:1.5,c:0,d:1,rgb:mh_eq:1:firebrick:black:sunset,hist:3:0' \
--pix 5000 --out lyap948_8_hist_3_0.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} fig 9.69, hist,3,0 ab}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_8ab_hist_3_0.png}}
fig 9.69
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:AB:-4:-4:4:4,a:-0.4,b:1.5,c:0,d:1,rgb:mh_eq:1:firebrick:black:sunset,hist:3:0' \
--pix 5000 --out lyap948_8ab_hist_3_0.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} fig 9.69, hist,3,0, aaab}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_8aaab_hist_3_0.png}}
fig 9.69
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:AAABB:-4:-4:4:4,a:-0.4,b:1.5,c:0,d:1,rgb:mh_eq:1:firebrick:black:sunset,hist:3:0' \
--pix 5000 --out lyap948_8aaab_hist_3_0.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} fig 9.69, hist,3,0, aaabb}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_8aaabb_hist_3_0.png}}
fig 9.69
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:AAABB:-4:-4:4:4,a:-0.4,b:1.5,c:0,d:1,rgb:mh_eq:1:firebrick:black:sunset,hist:3:0' \
--pix 5000 --out lyap948_8aaabb_hist_3_0.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} fig 9.69, hist,3,0, aaabbb}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_8aaabbb_hist_3_0.png}}
fig 9.69
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:AAABBB:-4:-4:4:4,a:-0.4,b:1.5,c:0,d:1,rgb:mh_eq:1:firebrick:black:sunset,hist:3:0' \
--pix 5000 --out lyap948_8aaabbb_hist_3_0.png --thumb 5000
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\section{{\tt eqn 948} fig 9.69, hist,3,0, mosaic}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_8mosaic_hist_3_0.png}}
fig 9.69
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A{5:8}B{1:4}:-4:-4:4:4,a:-0.4,b:1.5,c:0,d:1,rgb:mh_eq:1:firebrick:black:sunset,hist:3:0' \
--pix 2000 --out lyap948_8mosaic_hist_3_0.png --thumb 5000
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.70
\newpage
\section{{\tt eqn 948} location fig 9.70}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_36.png}}
fig 9.70
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:AB,a:1,b:2.1,c:0,d:1,ll:2.51:4.51,ul:4.5:6.5,lr:4.51:2.51,trans:200,iter:200,x0:0.4,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_36_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.71
\newpage
\section{{\tt eqn 948} location fig 9.71}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_37.png}}
fig 9.71
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2,a:1,b:2.1,c:0,d:1,ll:0.333:0.778,ul:0.744:1.189,lr:0.778:0.333,trans:1000,iter:1000,x0:0.4,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_37_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.72
\newpage
\section{{\tt eqn 948} location fig 9.72}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_38.png}}
fig 9.72
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:AB,a:1,b:1,c:0,d:1,ll:0:0.05,ul:0:9.95,lr:10:0.05,trans:200,iter:200,x0:0.4,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_38_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.73
\newpage
\section{{\tt eqn 948} location fig 9.73}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_39.png}}
fig 9.73
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:AAABB,a:-1,b:2.75,c:0,d:1,ll:0.702:1.282,ul:1.73:2.51,lr:1.451:0.65499,trans:200,iter:400,x0:0.6,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_39_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.74
\newpage
\section{{\tt eqn 948} location fig 9.74}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_40.png}}
fig 9.74
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2,a:-1,b:2.25,c:0,d:1,ll:0.195:1.205,ul:1.945:2.955,lr:1.205:0.195,trans:100,iter:400,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_40_hist.png
@


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.75
\newpage
\section{{\tt eqn 948} location fig 9.75}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_41.png}}
fig 9.75
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A3B,a:-1,b:1.5,c:0,d:1,ll:1.2:4.3,ul:4.9:8.,lr:4.3:1.2,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_41_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.76
\newpage
\section{{\tt eqn 948} location fig 9.76}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_42.png}}
fig 9.76
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:AAB,a:2.8,b:1.6,c:0,d:1,ll:3.729:4.444,ul:4.367:5.082,lr:4.444:3.792,trans:100,iter:200,x0:0.39,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_42_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.77
\newpage
\section{{\tt eqn 948} location fig 9.77}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_43.png}}
fig 9.77
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:AB,a:0.7,b:1.6,c:0,d:1,ll:0.87:2.58,ul:2.7:4.41,lr:2.58:0.87,trans:100,iter:200,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_43_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.78
\newpage
\section{{\tt eqn 948} location fig 9.78}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_44.png}}
fig 9.78
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:AB,a:-0.4,b:2,c:0,d:1,ll:3.606:3.954,ul:3.981:4.329,lr:3.954:3.606,trans:2000,iter:2000,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_44.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.79
\newpage
\section{{\tt eqn 948} location fig 9.79}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_45.png}}
fig 9.79
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A3B3,a:-0.2,b:2,c:0,d:1,ll:3.23:4.07,ul:3.78:4.62,lr:4.07:3.23,trans:400,iter:1000,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_45_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.80
\newpage
\section{{\tt eqn 948} location fig 9.80}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_46.png}}
fig 9.80
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:AB,a:-0.2,b:2,c:0,d:1,ll:4.34:4.67,ul:4.651:4.981,lr:4.67:4.34,trans:500,iter:1500,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_46.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.81
\newpage
\section{{\tt eqn 948} location fig 9.81}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_47.png}}
fig 9.81
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:-0.2,b:2,c:0,d:1,ll:3.665:3.955,ul:4.045:4.335,lr:3.955:3.665,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_47.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.82
\newpage
\section{{\tt eqn 948} location fig 9.82}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_48.png}}
fig 9.82
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A3B3,a:0.2,b:2.75,c:0,d:1,ll:0.265:0.535,ul:0.51:0.78,lr:0.535:0.265,trans:1500,iter:1500,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_48_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.83
\newpage
\section{{\tt eqn 948} location fig 9.83}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_49.png}}
fig 9.83
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:AB,a:0.5,b:2.5,c:0,d:1,ll:1.95:2.3915,ul:2.6905:3.144,lr:2.398:1.9506,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_49.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.84
\newpage
\section{{\tt eqn 948} location fig 9.84}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_50.png}}
fig 9.84
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2,a:-1.25,b:1.5,c:0,d:1,ll:0.24:4.92,ul:0.24:6.07,lr:1.22:4.92,trans:100,iter:200,x0:0.6,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_50_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.85
\newpage
\section{{\tt eqn 948} location fig 9.85}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_51.png}}
fig 9.85
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2,a:0.6,b:1.5,c:0,d:1,ll:2.2:3.2,ul:3.9:4.9,lr:3.2:2.2,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_51_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.86
\newpage
\section{{\tt eqn 948} location fig 9.86}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_52.png}}
fig 9.86
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:-2,b:2.5,c:0,d:1,ll:3.525:3.885,ul:3.824:4.184,lr:3.885:3.525,trans:400,iter:1000,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_52.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.87
\newpage
\section{{\tt eqn 948} location fig 9.87}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_53.png}}
fig 9.87
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0.25,b:2.3,c:0,d:1,ll:5.46:6.26,ul:5.76:6.56,lr:6.26:5.46,trans:200,iter:400,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_53.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.88
\newpage
\section{{\tt eqn 948} location fig 9.88}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_54.png}}
fig 9.88
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:1,b:2.25,c:0,d:1,ll:0.778:1.528,ul:1.271:2.021,lr:1.528:0.778,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_54.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.89
\newpage
\section{{\tt eqn 948} location fig 9.89}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_55.png}}
fig 9.89
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:1,b:2.25,c:0,d:1,ll:0.955:1.415,ul:1.249:1.709,lr:1.415:0.955,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_55.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.90
\newpage
\section{{\tt eqn 948} location fig 9.90}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_56.png}}
fig 9.90
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2,a:-0.4,b:2,c:0,d:1,ll:1.6:2,ul:1.99:2.39,lr:2:1.6,trans:100,iter:200,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_56_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.91
\newpage
\section{{\tt eqn 948} location fig 9.91}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_57.png}}
fig 9.91
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2,a:1.5,b:1.6,c:0,d:1,ll:2:3.15,ul:3.15:4.3,lr:3.15:2,trans:100,iter:200,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_57_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.92
\newpage
\section{{\tt eqn 948} location fig 9.92}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_58.png}}
fig 9.92
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:AB,a:0,b:2.5,c:0.5,d:1,ll:1.695:3.125,ul:2.455:3.885,lr:3.125:1.695,trans:400,iter:1000,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_58.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.93
\newpage
\section{{\tt eqn 948} location fig 9.93}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_59.png}}
fig 9.93
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A3B3,a:0,b:1.7,c:1.5,d:1,ll:1.59:2.37,ul:2.545:3.325,lr:2.36:1.6,trans:100,iter:200,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_59_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.94
\newpage
\section{{\tt eqn 948} location fig 9.94}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_60.png}}
fig 9.94
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A7B7,a:0,b:2.36,c:0.16,d:1,ll:10.155:10.6,ul:10.5085:10.9535,lr:10.60:10.155,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_60.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.95
\newpage
\section{{\tt eqn 948} location fig 9.95}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_61.png}}
fig 9.95
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0.2,b:2.3,c:0,d:1,ll:6.928:7.448,ul:7.65:8.18,lr:7.448:6.935,trans:100,iter:200,x0:0.3,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_61.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.96
\newpage
\section{{\tt eqn 948} location fig 9.96}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_62.png}}
fig 9.96
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2,a:0.7,b:2,c:0,d:1,ll:-0.912:-1.012,ul:-0.994:-1.094,lr:-1.012:-0.912,trans:800,iter:500,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_62_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.97
\newpage
\section{{\tt eqn 948} location fig 9.97}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_63.png}}
fig 9.97
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:2,c:1.25,d:1,ll:5.1283:4.9518,ul:5.2612:5.1886,lr:5.345:4.8302,trans:1000,iter:1000,x0:1.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_63.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.98
\newpage
\section{{\tt eqn 948} location fig 9.98}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_64.png}}
fig 9.98
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A3B3,a:0,b:2,c:1.25,d:1,ll:-0.778:-0.5766,ul:-0.557:-0.3296,lr:-0.5544:-0.77666,trans:3000,iter:3000,x0:1.5,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_64_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.99
\newpage
\section{{\tt eqn 948} location fig 9.99}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_65.png}}
fig 9.99
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A3B3,a:0,b:2,c:1.25,d:1,ll:5.84:5.44,ul:5.35:4.95,lr:5.44:5.84,trans:500,iter:500,x0:1.5,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_65_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.100
\newpage
\section{{\tt eqn 948} location fig 9.100}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_66.png}}
fig 9.100
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A3B3,a:0,b:2,c:1.25,d:1,ll:3.56:3.881,ul:3.56:4.75,lr:3.829:3.881,trans:500,iter:500,x0:1.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_66.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.101
\newpage
\section{{\tt eqn 948} location fig 9.101}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_67.png}}
fig 9.101
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2,a:0.6,b:1.5,c:0,d:1,ll:3.2199:3.3405,ul:3.338:3.4105,lr:3.297:3.2104,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_67_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.102
\newpage
\section{{\tt eqn 948} location fig 9.102}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_68.png}}
fig 9.102
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'map:eq948:A2B2,a:-1.25,b:1.5,c:0,d:1,ll:0.784:1.216,ul:1.3:1.732,lr:1.216:0.784,trans:1000,iter:1000,x0:0.6,rgb:mh_eq:1:firebrick:black:sunset,hist:3:3' \
--pix 5000 --out lyap948_68_hist.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.103
\newpage
\section{{\tt eqn 948} location fig 9.103}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_69.png}}
fig 9.103
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:-1,b:2.25,c:0,d:1,ll:5.6905:5.73,ul:5.7505:5.79,lr:5.73:5.6905,trans:2000,iter:2000,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_69.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.104
\newpage
\section{{\tt eqn 948} location fig 9.104}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_70.png}}
fig 9.104
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:-1,b:2.25,c:0,d:1,ll:1.171:1.499,ul:1.659:1.977,lr:1.489:1.1743,trans:100,iter:200,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_70.png
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.104
\newpage
\section{{\tt eqn 948} location fig 9.104, marvel}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_70_marvel.png}}
fig 9.104, marvel palettes
\end{center}

\vskip 1cm 


\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:-1,b:2.25,c:0,d:1,ll:1.171:1.499,ul:1.659:1.977,lr:1.489:1.1743,trans:100,iter:200,x0:0.5,rgb:multi:${glp("^marvel",9)}' \
--pix 2000 --out lyap948_70_marvel.png --thumb 5000
@



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% fig 9.105
\newpage
\section{{\tt eqn 948} location fig 9.105}

\vskip 1cm 

\begin{center}
\tcbox[
  enhanced, 
  boxrule=6pt, 
  colframe=black, 
  colback=black,
  left=0pt,right=0pt,top=0pt,bottom=0pt
]{\includegraphics[width=18cm,height=18cm]{lyap948_71.png}}
fig 9.105
\end{center}

\vskip 1cm 

<<, engine='bash', echo=TRUE, eval=run_code>>=
python lyapunov1.py --spec \
'eq948:A2B2,a:0.7,b:2,c:0,d:1,ll:4.8036:4.8856,ul:4.8952:4.9772,lr:4.8856:4.8036,trans:2000,iter:2000,x0:0.5,rgb:mh_eq:1:firebrick:black:sunset' \
--pix 5000 --out lyap948_71.png
@

\end{document}
